[package]
name = "my-limes"
version = "0.1.0"
authors = ["Chris Allen <cma@bitemyapp.com>"]

[dependencies]
chrono = "0.4.0"
egg-mode = "0.11.0"
dotenv = "0.9.0"
futures = "*"
serde = "*"
serde_derive = "*"
tokio-core = "0.1.10"
toml = "0.4"
xdg = "^2.1"
